---
- hosts: all
  sudo: yes
  tasks:
    - yum: name=libselinux-python state=present
    - selinux: state=disabled
    - shell: wget http://ftp.riken.jp/Linux/fedora/epel/RPM-GPG-KEY-EPEL-6 && rpm --import RPM-GPG-KEY-EPEL-6 && rm RPM-GPG-KEY-EPEL-6
    - copy: src=../files/epel.repo dest=/etc/yum.repos.d/epel.repo owner=root mode=755
    - yum: pkg=git state=installed
    - yum: pkg=gcc state=installed
    - yum: pkg=patch state=installed
    - yum: pkg=openssl-devel state=installed
    - yum: pkg=mysql-devel state=installed
    - yum: pkg=libcurl state=installed
    - yum: pkg=libcurl-devel state=installed
    - yum: pkg=bison state=installed
    - yum: pkg=bison-devel state=installed
    - yum: pkg=libjpeg-turbo state=installed
    - yum: pkg=libjpeg-turbo-devel state=installed
    - yum: pkg=libpng state=installed
    - yum: pkg=libpng-devel state=installed
    - yum: pkg=libmcrypt state=installed enablerepo=epel
    - yum: pkg=libmcrypt-devel state=installed enablerepo=epel
    - yum: pkg=readline state=installed
    - yum: pkg=readline-devel state=installed
    - yum: pkg=libtidy state=installed
    - yum: pkg=libtidy-devel state=installed
    - yum: pkg=autoconf state=installed
    - yum: pkg=automake state=installed
    - yum: pkg=libxml2-devel state=installed
    - yum: pkg=libxslt-devel state=installed
