---
- hosts: all
  sudo: yes
  tasks:
    - command: su - isucon bash -c 'git clone https://github.com/tagomoris/xbuild.git /home/isucon/.xbuild'
      args:
        creates: /home/isucon/.xbuild/ruby-install

    # ruby
    - command: su - isucon bash -c '/home/isucon/.xbuild/ruby-install 2.1.3 /home/isucon/.local/ruby'
      args:
        creates: /home/isucon/.local/ruby/bin/ruby
    - command: su - isucon bash -c '/home/isucon/env.sh gem install --no-rdoc --no-ri foreman'
      args:
        creates: /home/isucon/.local/ruby/bin/foreman
    - command: su - isucon bash -c 'cd /home/isucon/webapp/ruby; /home/isucon/env.sh bundle install'
    # node
    - command: su - isucon bash -c '/home/isucon/.xbuild/node-install v0.10.31 /home/isucon/.local/node'
      args:
        creates: /home/isucon/.local/node/bin/node
    - command: su - isucon bash -c 'cd /home/isucon/webapp/node; /home/isucon/env.sh npm install'
    # python
    - command: su - isucon bash -c '/home/isucon/.xbuild/python-install 2.7.8 /home/isucon/.local/python'
      args:
        creates: /home/isucon/.local/python/bin/python
    - command: su - isucon bash -c '/home/isucon/env.sh pip install gunicorn Flask MySQL-python'
      args:
        creates: /home/isucon/.local/python/bin/gunicorn
    # perl
    # - shell: su - isucon bash -c '/home/isucon/.xbuild/perl-install 5.20.0 /home/isucon/.local/perl; test -x /home/isucon/.local/perl/bin/perl'
    - command: su - isucon bash -c '/home/isucon/.xbuild/perl-install 5.20.0 /home/isucon/.local/perl'
      args:
        creates: /home/isucon/.local/perl/bin/perl
    - command: su - isucon bash -c 'cd /home/isucon/webapp/perl; /home/isucon/env.sh carton install'

    # php
    - command: su - isucon bash -c '/home/isucon/.xbuild/php-install 5.6.0 /home/isucon/.local/php'
      args:
        creates: /home/isucon/.local/php/bin/php
    - copy: src=../files/php.ini dest=/home/isucon/.local/php/etc/php.ini owner=isucon mode=644
